### ISSUE TITLE
Tracks part of network should be thicker at zoom 13 and 14

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#140]
Tennessee Valley Trail in Marin
15/37.8522/-122.5414

<img width="703" alt="screen shot 2017-02-23 at 14 07 06" src="https://cloud.githubusercontent.com/assets/853051/23281305/98fbfb34-f9d1-11e6-8db9-5a3657f5db7e.png">

<img width="662" alt="screen shot 2017-02-23 at 14 07 17" src="https://cloud.githubusercontent.com/assets/853051/23281283/8c1ec0d6-f9d1-11e6-8757-248564ca468f.png">

**Comment by sensescape** [comment]
It's not visible because Tennessee Valley Trail is part of the local network, which is not visible until z15.
But I sort of fixed it, I changed it so lcn now shows at z14 but only for tracks.
<img width="837" alt="screen shot 2017-02-23 at 3 29 34 pm" src="https://cloud.githubusercontent.com/assets/466585/23283866/29247582-f9dd-11e6-847b-6001ad0e0fe1.png">

**Comment by nvkelso** [comment]
Oops, I explained poorly. The yellow network should still be visible only at z15+ (like all the other local networks) – but for tracks that _are_ local networks (or really `network: true`?), their brown lines should be thicker line weight at zooms 13 and 14.

**Comment by sensescape** [comment]
ahhh ok

**Comment by sensescape** [comment]
<img width="740" alt="screen shot 2017-02-24 at 10 52 30 am" src="https://cloud.githubusercontent.com/assets/466585/23316470/66264526-fa7f-11e6-99ac-13f892f83f57.png">
<img width="705" alt="screen shot 2017-02-24 at 10 52 27 am" src="https://cloud.githubusercontent.com/assets/466585/23316469/6625e252-fa7f-11e6-9b53-8e13ad392ece.png">
this is done
