### ISSUE TITLE
Polish trails & cycleway styling

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#34]
- [x] Basic
- [ ] Polish

Make use of the `walking_network` property to adjust sizing, watch for widths inside of some minor landuse like cemetery and golf course, & etc.

**Comment by nvkelso** [comment]
Basic changes this week are looking pretty good :)

**Comment by nvkelso** [comment]
- [ ] Munich has crazy green lines everywhere, omg: 14/48.1324/11.5544
- [ ] London less so than Munich, but pretty intense. 14/51.5144/-0.1290
- [ ] SF looks good, so how to make Munich and London better while keeping SF hierarchy? 14/37.7852/-122.4749

**Comment by sensescape** [comment]
I'd like to try starting dotted lines at z15 instead of z16, I think this might help since they look too bold in some places. Help? It may or may not work, but let's see what it looks like. Tried to but kept breaking the styling of other trail lines. I was mainly working within here:
https://github.com/tangrams/outdoor-style/blob/26ceb763b0cb0ab57dad31b73c2186328237fda8/outdoor-style.yaml#L6712-L6784
Help?

**Comment by nvkelso** [comment]
Moving to next milestone. Let's look at it together when you're back to the conference.

**Comment by nvkelso** [comment]
Fixed the above in 66ad7467a50f35c1dc5df04bccdc8a95d7d70c88, but now some work remains for the new v0.8 Tangram dashing support.

**Comment by nvkelso** [comment]
See: https://github.com/tangrams/tangram/pull/312

**Comment by nvkelso** [comment]
(Let's just work on dashing for steps now, keep the circle style for footway for now.)

**Comment by nvkelso** [comment]
Looking good.
