### ISSUE TITLE
Create mobile app build

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#52]
Special branch of Eraser Map?

Requires new Tangram, and this YAML & assets

**Comment by westnordost** [comment]
Am I right in the assumption that this won't work with how the API keys are currently managed by the MapzenMap?

Currently MapView expects a `vector_tiles_key` in the string resources and will always append this string via the `TileHttpHandler` for any HTTP request made to retrieve tiles. But the `style.yaml` can theoretically have any number of and the outdoor-style actually _has_ two tile sources (vector and terrain) which possibly both require API keys.

I am writing this here because I am currently programming on top of tangram-es and came to the point where I had to decide where to most conveniently put the API key (i.e. arguments bundle in factory, simple setter, custom styleable xml attribute, application xml metadata or xml resource like Mapzen Android SDK) and noticed the issue with ... all these possibilities due to the fact that it depends on data sources defined in the `style.yaml` which API keys to append where.

So currently, the only correct solution **is** to put the API key(s) into the `style.yaml`. But this is broken for Android because of the said `TileHttpHandler`
After the import+global variables feature is completed for tangram, this could then be the permanent solution to the issue.

**Comment by nvkelso** [comment]
In the case of the elevation tiles, those don't require a key at all. 

It's a hack right now, but the vector tiles API key shouldn't be an issue for a beta build. Longer term, both the issues you bring up should be addressed, /cc @bcamper and @blair1618.

**Comment by nvkelso** [comment]
@blair1618 What Tangram release should I target to support all the features in the Outdoor style? Master?

**Comment by tallytalwar** [comment]
@nvkelso for ES, latest release [0.3.1](https://github.com/tangrams/tangram-es/releases/tag/0.3.1-android) has all the raster work and the unified point-text style work in it. For JS [0.8](https://github.com/tangrams/tangram/releases/tag/v0.8.0) should have everything needed for outdoor style.

We do plan to release a patched **0.3.2** release for ES with some core stability and performance fixes most likely today.

**Comment by nvkelso** [comment]
There's an Eraser Map release with this live now.
