### ISSUE TITLE
extruded buildings

### ISSUE THREAD

**Issue by nvkelso** [tangrams/outdoor-style#63]
Not a lot, just a little

**Comment by nvkelso** [comment]
Got this mostly working by using static `extrude` values like 20 and 100 and 200, but some of the building faces are still extruding up to the stratosphere. 

I suspect the building shader needs to be revised? @meetar for help!

<img width="1108" alt="screen shot 2016-06-15 at 16 23 54" src="https://cloud.githubusercontent.com/assets/853051/16100814/e52790f0-3315-11e6-9272-e3930f0b0d5e.png">

/cc @sensescape

**Comment by nvkelso** [comment]
It'd also be nice to remove the fisheye effect (so all buildings had an lower-right shadow at the top left of the screen and the bottom right of the screen).

**Comment by meetar** [comment]
On the case 🔎

**Comment by meetar** [comment]
Turns out the camera settings weren't being applied, so the default "perspective" camera type was used, which led to the "fisheye" effect – this is fixed by https://github.com/tangrams/outdoor-style/pull/69.

The "supertall" buildings were a bug in Tangram where `min_height` properties weren't being handled properly, which was discussed in https://github.com/tangrams/tangram/issues/337 and fixed by https://github.com/tangrams/tangram/commit/43dcac737e71e1b637d783238681415a0356a4d9.

**Comment by nvkelso** [comment]
@meetar @bcamper is https://github.com/tangrams/tangram/commit/43dcac737e71e1b637d783238681415a0356a4d9 in a released version of Tangram yet? I'd like to release the Outdoor style this week, seems like a nice to have for that.

**Comment by meetar** [comment]
Yep! 0.8.1 was released 5 days ago: https://github.com/tangrams/tangram/releases/tag/v0.8.1
The current outdoor-style index.html specifies 0.8 which means it will pull in any subreleases, which means the live demo should be showing the fix now.
